name: Build Zirconium Remix
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore: ["**/README.md"]
  schedule:
    - cron: "05 10 * * *"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      desktop: zirc
      image_name: zibubu
      image_desc: "Unofficial Atomic Ubuntu (Zirconium)"
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}